version: 2
general:
  branches:
    ignore:
      - gh-pages
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:2.1-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore --framework netstandard2 ./PeerTalk/src
      - run: dotnet test  -c Release --no-restore --framework netcoreapp2.0 ./PeerTalk/test/PeerTalkTests.csproj --filter TestCategory!=IPv6
      - run: dotnet build -c Release --no-restore --framework netstandard2 ./src
      - run: dotnet test  -c Release --no-restore --framework netcoreapp2.0 ./test --filter TestCategory!=IPv6
      - run: dotnet build -c Release --no-restore --framework netcoreapp2.0 ./IpfsServer

# Circle CI does not completely support IPv6
# see https://discuss.circleci.com/t/ipv6-support/13571
