language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: required

install:
  - dotnet restore

script:
  - dotnet build -c Release --no-restore --framework netstandard2 ./PeerTalk/src
  - dotnet test  -c Release --no-restore --framework netcoreapp2.0 ./PeerTalk/test/PeerTalkTests.csproj
  - dotnet build -c Release --no-restore --framework netstandard2 ./src
  - dotnet test  -c Release --no-restore --framework netcoreapp2.0 ./test
