name: Publish to Nuget

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -p:Configuration=Release
    
    # Pre-publish unit test runs is disabled.
    # The codebase is old, and many things are broken in the latest HTTP API.
    # It'll take some time before we fully fix all the issues.
    # - name: Test
    #  run: dotnet test --no-build --verbosity normal -p:Configuration=Release

    - name: Publish to NuGet
      run: dotnet nuget push "/home/runner/work/net-ipfs-http-client/net-ipfs-http-client/src/bin/Release/IpfsShipyard.Ipfs.Http.Client.*.*.*.nupkg" --skip-duplicate --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json
      